apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "skiff-service.fullname" . }}
  labels:
    {{- include "skiff-service.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          labels:
            {{- include "skiff-service.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "skiff-service.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- if or .Values.env .Values.secretEnv }} # Check if any env vars are defined
              env:
                {{- if .Values.env }}
                {{- range $key, $value := .Values.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- end }}
                {{- if .Values.secretEnv }}
                {{- range $key, $value := .Values.secretEnv }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $value.secretName }}
                      key: {{ $value.secretKey }}
                {{- end }}
                {{- end }}
              {{- end }}
              {{- if .Values.commands }}
              command: {{ .Values.commands }}
              {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
