{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "skiff-service.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skiff-service.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
{{- end }}
