---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.appConfig.tenant_id }}-{{ include "workspace-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "workspace-service.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - podss
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stable.indocpilot.com
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.azure.com
  resources:
  - virtualmachines
  verbs:
  - get
  - list
- apiGroups:
  - network.azure.com
  resources:
  - virtualnetworks
  - publicipaddresses
  - networkinterfaces
  - virtualnetworkssubnets
  - networksecuritygroups
  verbs:
  - get
  - list
- apiGroups:
  - resources.azure.com
  resources:
  - resourcegroups
  verbs:
  - get
  - list
