{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
{{- if not .Values.appConfig.tenant_id }}
  name: "workspace-manager-rolebinding"
{{- else }}
  name: "workspace-manager-rolebinding-{{ .Values.appConfig.tenant_id }}"
{{- end}}
  labels:
    {{- include "jupyterhub-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- if not .Values.appConfig.tenant_id }}
  name: "workspace-manager"
{{- else }}
  name: "workspace-manager-{{ .Values.appConfig.tenant_id }}"
{{- end}}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
{{- if not .Values.appConfig.tenant_id }}
  namespace: "utility"
{{- else }}
  namespace: "{{ .Values.appConfig.tenant_id }}-utility"
{{- end}}
{{- end }}
