{{- if or (eq .Values.multitenant.enable false) (eq .Values.azureOperatorMode "webhooks") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azureserviceoperator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azureserviceoperator-proxy-role
subjects:
- kind: ServiceAccount
  name: azureserviceoperator-default
  namespace: {{ .Release.Namespace }}
{{- end }}
