job:
  name: "custom-job"
  restartPolicy: Never
  ttlSecondsAfterFinished: 100

container:
  name: "my-container"
  image:
    repository: ""
    tag: ""
  env: {}
  extraEnvYaml: {}

volumes: {}

volumeMounts: {}

serviceAccount:
  create: false
  annotations: {}
  name: "base-job-sa"
  rules: []
