dependencies:
  - name: mysql
    repository: https://charts.helm.sh/stable
    version: 1.4.0
    condition: mysql.enabled
  - name: postgresql
    repository: https://charts.helm.sh/stable
    version: 7.6.0
    condition: postgresql.enabled
