apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metadata-service.fullname" . }}
  labels:
    {{- include "metadata-service.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
    {{- if .Values.updateStrategy }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metadata-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metadata-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "init{{ .Values.name }}"
          image: "{{ .Values.image.repository }}:alembic-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.initCommand }}
          {{- with .Values.initCommand }}
          command: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.initArgs }}
          {{- with .Values.initArgs }}
          args: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          env:
###################### START OF APP CONFIG #############################   
          - name: port
            value: {{ .Values.appConfig.port | quote }}
          - name: CONFIG_CENTER_ENABLED
            value: {{ .Values.appConfig.config_center_enabled | quote }}
          - name: CONFIG_CENTER_BASE_URL
            value: {{ .Values.appConfig.config_center_base_url | quote }}
          - name: env
            value: {{ .Values.appConfig.env | quote }}
          - name: srv_namespace
            value: {{ .Values.appConfig.srv_namespace | quote }}

#kafka
          - name: KAFKA_URL
            value: {{ .Values.appConfig.KAFKA_URL | quote }}
#if tenant id is not set
{{- if not .Values.appConfig.tenant_id }}
          - name: KAFKA_TOPIC
            value: {{ .Values.appConfig.KAFKA_TOPIC | quote }}
{{- else }}
          - name: KAFKA_TOPIC
            value: "{{.Values.appConfig.tenant_id}}.metadata.items"
{{- end}}

# generate project
          - name: DCM_PROJECT_ID
            value: {{ .Values.appConfig.DCM_PROJECT_ID | quote }}

# run migrations
          - name: RUN_MIGRATIONS
            value: {{ .Values.appConfig.RUN_MIGRATIONS | quote }}

# auth_host
{{- if not .Values.appConfig.tenant_id }}
          - name: AUTH_HOST
            value: "http://auth.utility:5061"
{{- else }}
          - name: AUTH_HOST
            value: "http://auth.{{.Values.appConfig.tenant_id}}-utility:5061"
{{- end}}
  
# Relational Database 
{{- if not .Values.appConfig.tenant_id }}
          - name: OPSDB_UTILITY_HOST
            value: {{ .Values.appConfig.OPSDB_UTILITY_HOST | quote }}
{{- else }}
          - name: OPSDB_UTILITY_HOST
            value: "postgres.{{ .Values.appConfig.tenant_id }}-utility"
{{- end}}

          - name: OPSDB_UTILITY_PORT
            value: {{ .Values.appConfig.OPSDB_UTILITY_PORT | quote }}
          - name: OPSDB_UTILITY_USERNAME
            value: {{ .Values.appConfig.OPSDB_UTILITY_USERNAME | quote }}
          - name: METADATA_SCHEMA
            value: {{ .Values.appConfig.METADATA_SCHEMA | quote }}

###################### END OF APP CONFIG #############################
{{- if .Values.extraEnv }}
  {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.envSecrets }}
  {{- range $key, $secret :=  .Values.envSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret }}
                key: {{ $key | quote }}
  {{- end }}
{{- end }}
{{- with .Values.extraEnvYaml }}
          {{- toYaml . | nindent 10 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:metadata-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          {{- with .Values.command }}
          command: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.args }}
          {{- with .Values.args }}
          args: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          env:
###################### START OF APP CONFIG #############################   
          - name: port
            value: {{ .Values.appConfig.port | quote }}
          - name: CONFIG_CENTER_ENABLED
            value: {{ .Values.appConfig.config_center_enabled | quote }}
          - name: CONFIG_CENTER_BASE_URL
            value: {{ .Values.appConfig.config_center_base_url | quote }}
          - name: env
            value: {{ .Values.appConfig.env | quote }}
          - name: srv_namespace
            value: {{ .Values.appConfig.srv_namespace | quote }}

#kafka
          - name: KAFKA_URL
            value: {{ .Values.appConfig.KAFKA_URL | quote }}
#if tenant id is not set
{{- if not .Values.appConfig.tenant_id }}
          - name: KAFKA_TOPIC
            value: {{ .Values.appConfig.KAFKA_TOPIC | quote }}
{{- else }}
          - name: KAFKA_TOPIC
            value: "{{.Values.appConfig.tenant_id}}.metadata.items"
{{- end}}

# generate project
          - name: DCM_PROJECT_ID
            value: {{ .Values.appConfig.DCM_PROJECT_ID | quote }}

# run migrations
          - name: RUN_MIGRATIONS
            value: {{ .Values.appConfig.RUN_MIGRATIONS | quote }}

# auth_host
{{- if not .Values.appConfig.tenant_id }}
          - name: AUTH_HOST
            value: "http://auth.utility:5061"
{{- else }}
          - name: AUTH_HOST
            value: "http://auth.{{.Values.appConfig.tenant_id}}-utility:5061"
{{- end}}
  
# Relational Database 
{{- if not .Values.appConfig.tenant_id }}
          - name: OPSDB_UTILITY_HOST
            value: {{ .Values.appConfig.OPSDB_UTILITY_HOST | quote }}
{{- else }}
          - name: OPSDB_UTILITY_HOST
            value: "postgres.{{ .Values.appConfig.tenant_id }}-utility"
{{- end}}

          - name: OPSDB_UTILITY_PORT
            value: {{ .Values.appConfig.OPSDB_UTILITY_PORT | quote }}
          - name: OPSDB_UTILITY_USERNAME
            value: {{ .Values.appConfig.OPSDB_UTILITY_USERNAME | quote }}
          - name: METADATA_SCHEMA
            value: {{ .Values.appConfig.METADATA_SCHEMA | quote }}

###################### END OF APP CONFIG #############################
{{- if .Values.extraEnv }}
  {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.envSecrets }}
  {{- range $key, $secret :=  .Values.envSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret }}
                key: {{ $key | quote }}
  {{- end }}
{{- end }}
{{- with .Values.extraEnvYaml }}
          {{- toYaml . | nindent 10 }}
{{- end }}
          ports:
              - name: http
                containerPort: {{ .Values.container.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.extraVolumes }}
      volumes:
        {{- toYaml .Values.extraVolumes | nindent 10 }}
      {{- end }}
