---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: guacamole-manager-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: guacamole
    app.kubernetes.io/part-of: guacamole
    app.kubernetes.io/managed-by: kustomize
  name: guacamole-manager-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - stable.indocpilot.io
  resources:
  - guacamoles
  - guacamoles/status
  - guacamoles/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "storage.k8s.io"
  resources:
  - "storageclasses"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "persistentvolumes"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "persistentvolumeclaims"
  - "secrets"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- verbs:
  - "*"
  apiGroups:
  - "networking.k8s.io"
  resources:
  - "ingresses"
