apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
    {{- if .Values.updateStrategy }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "notification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "notification-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "init{{ .Values.name }}"
          image: "{{ .Values.image.repository }}:alembic-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.initCommand }}
          {{- with .Values.initCommand }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.initArgs }}
          {{- with .Values.initArgs }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          env:
###################### START OF APP CONFIG #############################
# Relational Database
{{- if not .Values.appConfig.tenant_id }}
          - name: RDS_HOST
            value: {{ .Values.appConfig.RDS_HOST | quote }}
{{- else }}
          - name: RDS_HOST
            value: "postgres.{{ .Values.appConfig.tenant_id }}-utility"
{{- end}}

          - name: RDS_PORT
            value: {{ .Values.appConfig.RDS_PORT | quote }}
          - name: RDS_USER
            value: {{ .Values.appConfig.RDS_USER | quote }}
          - name: RDS_DB_NAME
            value: {{ .Values.appConfig.RDS_DB_NAME | quote }}
          - name: RDS_ECHO_SQL_QUERIES
            value: {{ .Values.appConfig.RDS_ECHO_SQL_QUERIES | quote }}
###################### END OF APP CONFIG #############################
{{- if .Values.extraEnv }}
  {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.envSecrets }}
  {{- range $key, $secret :=  .Values.envSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret }}
                key: {{ $key | quote }}
  {{- end }}
{{- end }}
{{- with .Values.extraEnvYaml }}
          {{- toYaml . | nindent 10 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:notification-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.args }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          env:
###################### START OF APP CONFIG #############################
          - name: port
            value: {{ .Values.appConfig.port | quote }}
          - name: CONFIG_CENTER_ENABLED
            value: {{ .Values.appConfig.config_center_enabled | quote }}
          - name: CONFIG_CENTER_BASE_URL
            value: {{ .Values.appConfig.config_center_base_url | quote }}
          - name: HOST
            value: {{ .Values.appConfig.HOST | quote }}
          - name: WORKERS
            value: {{ .Values.appConfig.WORKERS | quote }}
          - name: PLATFORM_NAME
            value: {{ .Values.appConfig.PLATFORM_NAME | quote }}
# email
          - name: POSTFIX
            value: {{ .Values.appConfig.POSTFIX | quote }}
          - name: POSTFIX_URL
            value: {{ .Values.appConfig.POSTFIX_URL | quote }}
          - name: POSTFIX_PORT
            value: {{ .Values.appConfig.POSTFIX_PORT | quote }}
          - name: EMAIL_ATTACHMENT_MAX_SIZE_BYTES
            value: {{ .Values.appConfig.EMAIL_ATTACHMENT_MAX_SIZE_BYTES | quote }}
          - name: SMTP_PORT
            value: {{ .Values.appConfig.SMTP_PORT | quote }}
          - name: SMTP_USER
            value: {{ .Values.appConfig.SMTP_USER | quote }}
          - name: SMTP_PASS
            value: {{ .Values.appConfig.SMTP_PASS | quote }}
          - name: SMTP_STARTTLS
            value: {{ .Values.appConfig.SMTP_STARTTLS | quote }}

# Relational Database
{{- if not .Values.appConfig.tenant_id }}
          - name: RDS_HOST
            value: {{ .Values.appConfig.RDS_HOST | quote }}
{{- else }}
          - name: RDS_HOST
            value: "postgres.{{ .Values.appConfig.tenant_id }}-utility"
{{- end}}

          - name: RDS_PORT
            value: {{ .Values.appConfig.RDS_PORT | quote }}
          - name: RDS_USER
            value: {{ .Values.appConfig.RDS_USER | quote }}
          - name: RDS_DB_NAME
            value: {{ .Values.appConfig.RDS_DB_NAME | quote }}
          - name: RDS_ECHO_SQL_QUERIES
            value: {{ .Values.appConfig.RDS_ECHO_SQL_QUERIES | quote }}

            ## Telemetry
          - name: OPEN_TELEMETRY_ENABLED
            value: {{ .Values.appConfig.OPEN_TELEMETRY_ENABLED | quote }}
          - name: OPEN_TELEMETRY_HOST
            value: {{ .Values.appConfig.OPEN_TELEMETRY_HOST | quote }}
          - name: OPEN_TELEMETRY_PORT
            value: {{ .Values.appConfig.OPEN_TELEMETRY_PORT | quote }}
          - name: KAFKA_SERVICE
            value: {{ .Values.appConfig.KAFKA_SERVICE | quote }}
###################### END OF APP CONFIG #############################

{{- if .Values.extraEnv }}
  {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.envSecrets }}
  {{- range $key, $secret :=  .Values.envSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret }}
                key: {{ $key | quote }}
  {{- end }}
{{- end }}
{{- with .Values.extraEnvYaml }}
          {{- toYaml . | nindent 10 }}
{{- end }}
          ports:
              - name: http
                containerPort: {{ .Values.container.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.extraVolumes }}
      volumes:
        {{- toYaml .Values.extraVolumes | nindent 10 }}
      {{- end }}
