apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "guacd.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.guacd.replicaCount }}
  selector:
    matchLabels:
       {{- include "guacd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guacd.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.guacd.image.repository }}:{{ .Values.guacd.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.guacd.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "guacamole.fullname" . }}
          ports:
            - name: guacd
              containerPort: {{ .Values.guacd.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

