apiVersion: v1
kind: PersistentVolume
metadata:
  name: guacamole-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"