apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "guacamole.labels" . | indent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.guacamole.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.guacamole.postgresql.auth.password | b64enc | quote }}
  GLOBAL_POSTGRES_USER: {{ .Values.global.postgresql.auth.username | b64enc | quote }}
  GLOBAL_POSTGRES_PASSWORD: {{ .Values.global.postgresql.auth.password | b64enc | quote }}
  WEBAPP_CONTEXT: {{ "ROOT" | b64enc | quote }}
