apiVersion: v1
kind: Secret
metadata:
  name: {{include "guacamole.fullname" .}}
  labels:
{{ include "guacamole.labels" . | indent 4 }}
type: Opaque
data:
  {{- $secretName :=  include "guacamole.fullname" . }}
  {{- $guacSecretData := (lookup "v1" "Secret" .Release.Namespace $secretName).data }}
  {{- if $guacSecretData }}
    {{- $guacPostgresPassword := index $guacSecretData "POSTGRES_PASSWORD" }}
      POSTGRES_PASSWORD: {{ $guacPostgresPassword }}
  {{- else }}
      {{- $newPass := randAlphaNum 10 | b64enc | quote }}
      POSTGRES_PASSWORD: {{ $newPass }}
  {{- end}}
  {{- $postgresSecretData := (lookup "v1" "Secret" .Release.Namespace .Values.guacamole.postgresql.auth.hostname).data }}
  {{- if $postgresSecretData }}
    {{- $postgresPassword := index $postgresSecretData "postgres-password" }}
      GLOBAL_POSTGRES_PASSWORD: {{ $postgresPassword }}
  {{- end}}
