apiVersion: v1
kind: Service
metadata:
  name: guacd
  labels:
{{ include "guacamole.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.guacd.port }}
      targetPort: guacd
      protocol: TCP
      name: guacd
  selector:
    {{- include "guacd.selectorLabels" . | nindent 4 }}
