apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bff.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "bff.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
    {{- if .Values.updateStrategy }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bff.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bff.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repositoryBff }}:{{ .Values.image.tagBff | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.container.port }}
            - containerPort: {{ .Values.container.portalPort }}
          imagePullPolicy: {{ .Values.image.pullPolicyBff }}
          {{- if .Values.command }}
          {{- with .Values.command }}
          command: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.args }}
          {{- with .Values.args }}
          args: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          env:
###################### START OF APP CONFIG #############################    
          - name: CONFIG_CENTER_ENABLED
            value: {{ .Values.appConfig.config_center_enabled | quote }}
          - name: CONFIG_CENTER_BASE_URL
            value: {{ .Values.appConfig.config_center_base_url | quote }}
          - name: env
            value: {{ .Values.appConfig.env | quote }}
          - name: PROJECT_NAME
            value: {{ .Values.appConfig.PROJECT_NAME | quote }}
          - name: KEYCLOAK_REALM
            value: {{ .Values.appConfig.KEYCLOAK_REALM | quote }}  

# workers
          - name: WORKERS
            value: {{ .Values.appConfig.WORKERS | quote }}

# deprecated
          - name: KG_SERVICE
            value: "http://kg.utility:5064"

# domains and paths
          - name: SITE_DOMAIN
            value: {{ .Values.appConfig.SITE_DOMAIN | quote }}
          - name: KONG_PATH
            value: {{ .Values.appConfig.KONG_PATH | quote }}
{{- if not .Values.appConfig.INVITATION_URL_LOGIN }}
          - name: INVITATION_URL_LOGIN
            value: "{{ .Values.appConfig.SITE_DOMAIN }}/login"
{{- else }}
          - name: INVITATION_URL_LOGIN
            value: {{ .Values.appConfig.INVITATION_URL_LOGIN | quote }}
{{- end }}

# zones
          - name: CORE_ZONE_LABEL
            value: {{ .Values.appConfig.CORE_ZONE_LABEL | quote }}
          - name: GREENROOM_ZONE_LABEL
            value: {{ .Values.appConfig.GREENROOM_ZONE_LABEL | quote }}  
      
#email 
          - name: EMAIL_SUPPORT
            value: {{ .Values.appConfig.EMAIL_SUPPORT | quote }}
          - name: EMAIL_ADMIN
            value: {{ .Values.appConfig.EMAIL_ADMIN | quote }}  
          - name: EMAIL_HELPDESK
            value: {{ .Values.appConfig.EMAIL_HELPDESK | quote }}  

# resource request admin
          - name: RESOURCE_REQUEST_ADMIN
            value: {{ .Values.appConfig.RESOURCE_REQUEST_ADMIN | quote }}


# redis
{{- if not .Values.appConfig.tenant_id }}
          - name: REDIS_HOST
            value: {{ .Values.appConfig.REDIS_HOST | quote }}
{{- else }}
          - name: REDIS_HOST
            value: "redis-master.{{ .Values.appConfig.tenant_id }}-redis"
{{- end }}
          - name: REDIS_PORT
            value: {{ .Values.appConfig.REDIS_PORT | quote }}


# Microservices connections
#if tenant id is not set
{{- if not .Values.appConfig.tenant_id }}
          - name: AUTH_SERVICE
            value: "http://auth.utility:5061"
          - name: APPROVAL_SERVICE
            value: "http://approval.utility:8000"
          - name: DATAOPS_SERVICE
            value: "http://dataops.utility:5063"
          - name: DATASET_SERVICE
            value: "http://dataset.utility:5081"
          - name: METADATA_SERVICE
            value: "http://metadata.utility:5066"
          - name: PROJECT_SERVICE
            value: "http://project.utility:5064"
          - name: NOTIFY_SERVICE
            value: "http://notification.utility:5065"
          - name: UPLOAD_SERVICE
            value: "http://upload.greenroom:5079"      
          - name: DOWNLOAD_SERVICE_CORE
            value: "http://download.core:5077" 
          - name: DOWNLOAD_SERVICE_GR
            value: "http://download.greenroom:5077"    
          - name: SEARCH_SERVICE
            value: "http://search.utility:5064"
          - name: WORKSPACE_SERVICE
            value: "http://workspace.utility:5068"      
{{- else }}
          - name: AUTH_SERVICE
            value: "http://auth.{{ .Values.appConfig.tenant_id }}-utility:5061"
          - name: APPROVAL_SERVICE
            value: "http://approval.{{ .Values.appConfig.tenant_id }}-utility:8000"
          - name: DATAOPS_SERVICE
            value: "http://dataops.{{ .Values.appConfig.tenant_id }}-utility:5063"
          - name: DATASET_SERVICE
            value: "http://dataset.{{ .Values.appConfig.tenant_id }}-utility:5081"
          - name: METADATA_SERVICE
            value: "http://metadata.{{ .Values.appConfig.tenant_id }}-utility:5066"
          - name: PROJECT_SERVICE
            value: "http://project.{{ .Values.appConfig.tenant_id }}-utility:5064"
          - name: NOTIFY_SERVICE
            value: "http://notification.{{ .Values.appConfig.tenant_id }}-utility:5065"
          - name: UPLOAD_SERVICE
            value: "http://upload.{{ .Values.appConfig.tenant_id }}-greenroom:5079"  
          - name: DOWNLOAD_SERVICE_CORE
            value: "http://download.{{ .Values.appConfig.tenant_id }}-core:5077" 
          - name: DOWNLOAD_SERVICE_GR
            value: "http://download.{{ .Values.appConfig.tenant_id }}-greenroom:5077"       
          - name: SEARCH_SERVICE
            value: "http://search.{{ .Values.appConfig.tenant_id }}-utility:5064"
          - name: WORKSPACE_SERVICE
            value: "http://workspace.{{ .Values.appConfig.tenant_id }}-utility:5068"  
{{- end}}
###################### END OF APP CONFIG #############################
{{- if .Values.extraEnv }}
  {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- with .Values.extraEnvYaml }}
          {{- toYaml . | nindent 10 }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
