apiVersion: v1
kind: Service
metadata:
  name: {{ include "bff.fullname" . }}-sidecar
  labels:
    {{- include "bff.labelsSidecar" . | nindent 4 }}
spec:
  type: {{ .Values.serviceSidecar.type }}
  ports:
    - port: {{ .Values.serviceSidecar.port }}
      targetPort: {{ .Values.serviceSidecar.targetPort }}
      protocol: TCP
      name: {{ include "bff.fullname" . }}-sidecar
  selector:
    {{- include "bff.selectorLabelsSidecar" . | nindent 4 }}
