# Default values for dataset-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: dataset
  tag: 25
  pullPolicy: Always

appConfig:
  port: 5081
  config_center_enabled: false
  config_center_base_url: http://common.utility:5062/
  env: "dev"


  tenant_id: ""

  OPEN_TELEMETRY_ENABLED: true
  DATASET_FILE_FOLDER: "data"
  DATASET_SCHEMA_FOLDER: "schema"
  DATASET_CODE_REGEX: "^[a-z0-9]{3,32}$"
  OPSDB_UTILITY_HOST: "postgres.utility"
  OPSDB_UTILITY_PORT: "5432"
  OPSDB_UTILITY_USERNAME: "postgres"
  RDS_DBNAME: "dataset"
  REDIS_HOST: "redis-master.redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  RUN_MIGRATIONS_ON_BUILD: "false"
  DOWNLOAD_TOKEN_EXPIRE_AT: "5"
  MAX_PREVIEW_SIZE: "500000"
  ESSENTIALS_NAME: "essential.schema.json"
  ESSENTIALS_TPL_NAME: "Essential"
  ALEMBIC_CONFIG: "migrations/alembic.ini"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

container:
  port: 5081

service:
  type: ClusterIP
  port: 80

podAnnotations: {}

deploymentAnnotations: {}

podSecurityContext: {}

securityContext: {}

imagePullSecrets: []

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: {}

extraEnvYaml: {}

readinessProbe: []

extraVolumeMounts: []

extraVolumes: []

updateStrategy: []
