apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search-service.fullname" . }}
  labels:
    {{- include "search-service.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
    {{- if .Values.updateStrategy }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "search-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "search-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "init{{ .Values.name }}"
          image: "{{ .Values.image.repository }}:init-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.initCommand }}
          {{- with .Values.initCommand }}
          command: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.initArgs }}
          {{- with .Values.initArgs }}
          args: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          env:
###################### START OF APP CONFIG #############################  
          - name: ELASTICSEARCH_URI
            value: {{ .Values.appConfig.ELASTICSEARCH_URI | quote}}
{{- if .Values.extraEnv }}
  {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.envSecrets }}
  {{- range $key, $secret :=  .Values.envSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret }}
                key: {{ $key | quote }}
  {{- end }}
{{- end }}
{{- with .Values.extraEnvYaml }}
          {{- toYaml . | nindent 10 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:search-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
###################### START OF APP CONFIG #############################         
          - name: CONFIG_CENTER_ENABLED
            value: {{ .Values.appConfig.config_center_enabled | quote }}
          - name: CONFIG_CENTER_BASE_URL
            value: {{ .Values.appConfig.config_center_base_url | quote }}
          - name: env
            value: {{ .Values.appConfig.env | quote }}
          - name: srv_namespace
            value: {{ .Values.appConfig.srv_namespace | quote }}
          - name: HOST
            value: {{ .Values.appConfig.HOST }}           
          - name: PORT
            value: {{ .Values.appConfig.PORT | quote }}  
          - name: WORKERS
            value: {{ .Values.appConfig.WORKERS | quote }}
          - name: ELASTICSEARCH_URI
            value: {{ .Values.appConfig.ELASTICSEARCH_URI | quote}}
          ## Telemetry
          - name: OPEN_TELEMETRY_ENABLED
            value: {{ .Values.appConfig.OPEN_TELEMETRY_ENABLED | quote }}
          - name: OPEN_TELEMETRY_HOST
            value: {{ .Values.appConfig.OPEN_TELEMETRY_HOST | quote }}
          - name: OPEN_TELEMETRY_PORT
            value: {{ .Values.appConfig.OPEN_TELEMETRY_PORT | quote }}
{{- if .Values.extraEnv }}
  {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- with .Values.extraEnvYaml }}
          {{- toYaml . | nindent 10 }}
{{- end }}
          ports:
              - name: http
                containerPort: {{ .Values.container.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.extraVolumes }}
      volumes:
        {{- toYaml .Values.extraVolumes | nindent 10 }}
      {{- end }}
