# Default values for approval-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: approval
  pullPolicy: Always
  tag: 26

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name:

container:
  port: 8000

appConfig:
  env: "dev"
  CONFIG_CENTER_ENABLED: false
  CONFIG_CENTER_BASE_URL:
podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

readinessProbe: {}

updateStrategy: {}

extraEnv: {}

extraEnvYaml: {}
