# Default values for approval-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: approval
  pullPolicy: Always
  tag: 26

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name:

container:
  port: 8000

appConfig:
  env: "dev"
  port: 8000
  CONFIG_CENTER_ENABLED: false
  CONFIG_CENTER_BASE_URL: "http://common.utility:5062/"

  tenant_id: ""

  HOST: 0.0.0.0
  SRV_NAMESPACE: service_approval

  # Microservices connections
  AUTH_SERVICE: "http://auth.utility:5061"
  DATAOPS_SERVICE: "http://dataops.utility:5063"
  EMAIL_SERVICE: "http://notification.utility:5065"
  METADATA_SERVICE: "http://metadata.utility:5066"
  PROJECT_SERVICE: "http://project.utility:5064"
  NOTIFICATION_SERVICE: "http://notification.utility:5065"

  # Relation Database Service
  RDS_SCHEMA_DEFAULT: "pilot_approval"
  RDS_DB: "approval"
  RDS_HOST: "postgres.utility"
  RDS_USER: "postgres"
  RDS_PORT: 5432

  # Redis Service
  REDIS_HOST: "redis-master.redis"
  REDIS_PORT: 6379
  REDIS_DB: 0

  # Open telemetry
  OPEN_TELEMETRY_ENABLED: false
  OPEN_TELEMETRY_HOST: 127.0.0.1
  OPEN_TELEMETRY_PORT: 6831

  # Email configuration
  EMAIL_SUPPORT: "pilotplatform_support@indocresearch.com"



podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

readinessProbe: {}

updateStrategy: {}

extraEnv: {}

extraEnvYaml: {}
