# Default values for bff-cli-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: bff-cli
  tag: 135
  pullPolicy: Always

appConfig:
  port: 5080
  env: "dev"
  config_center_enabled: false
  config_center_base_url: http://common.utility:5062/
  srv_namespace: service_bff-cli

  tenant_id: ""

  log_level: info
  namespace: utility
  OPEN_TELEMETRY_ENABLED: "True"

  CLI_PUBLIC_KEY_PATH: "/var/run/secrets/guacamole/jwt-key.pub"
  GREEN_ZONE_LABEL: "Greenroom"
  CORE_ZONE_LABEL: "Core"

  REDIS_HOST: "redis-master.redis"
  REDIS_DB: "0"
  REDIS_PORT: "6379"
  HPC_SERVICE: ""
  KG_SERVICE: ""
  ATLAS_API: "http://atlas.utility:21000"
  ATLAS_ENTITY_TYPE: "metadata_items"

  JUPYTER_IP_LOWER: "15.0.0.0"
  JUPYTER_IP_UPPER: "15.0.255.255"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: 

container:
  port: 5080

service:
  type: ClusterIP
  port: 5080

podAnnotations: {}
deploymentAnnotations: {}

podSecurityContext: {}

securityContext: {}

imagePullSecrets: []

command:
  - "/bin/bash"
args:
  - "-c"
  - "./gunicorn_starter.sh"

ingress:
  enabled: false

resources:
  limits:
    cpu: "1"
    memory: 500Mi
  requests:
    cpu: "10m"
    memory: 10Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: {}

extraEnvYaml: {}

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 5080

extraVolumeMounts: []

extraVolumes: []

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 33%
  type: RollingUpdate
