cronjob:
  name: "custom-cronjob"
  # format
  # MIN HOUR DAY MONTH DAY_OF_WEEK
  schedule: "00 00 * * *"
  restartPolicy: Never
  ttlSecondsAfterFinished: 100

container:
  name: "my-container"
  image:
    repository: ""
    tag: ""
  env: {}
  extraEnvYaml: {}

volumes: {}

volumeMounts: {}

serviceAccount:
  create: false
  annotations: {}
  name: "base-cronjob-sa"
  rules: []
