cronjob:
  name: "custom-cronjob"
  # format
  # MIN HOUR DAY MONTH DAY_OF_WEEK
  schedule: "00 00 * * *"
  restartPolicy: Never
  ttlSecondsAfterFinished: 100

container:
  name: "my-container"
  image:
    repository: ""
    tag: ""
  env: []  
  # Optional: Define environment variables as a list of { name, value }
  # Example:
  # - name: PATH
  #   value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/shared"
  # - name: keycloak_device_client_id
  #   value: "cli"

volume:
  enabled: false  # Optional: Define if a volume is needed
  name: my-volume
  claimName: my-claim
  mountPath: "/tmp/volume"
