# Default values for queue-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pilotdataplatform.azurecr.io/queue/consumer
  tag: 106
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name: ""

container:
  port: 6060

appConfig:
  bids_validator_app_version: edge
  filecopy_app_version: edge
  env: "dev"
  CONFIG_CENTER_ENABLED: false
  CONFIG_CENTER_BASE_URL:
  KAFKA_URL: "kafka.utility:9092"
  tenant_id: ""
  RDS_HOST: "postgres.utility"
  RDS_PORT: "5432"


podAnnotations: {}

deploymentAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 6060

ingress:
  enabled: false

resources:
  requests:
    memory: "50Mi"
    cpu: "10m"
  limits:
    memory: "1000Mi"
    cpu: "1"

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

readinessProbe: {}

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 33%
  type: RollingUpdate

extraEnv: {}

extraEnvYaml: {}
