apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "workspace-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: workspace-controller-manager-metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "workspace-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "workspace-operator.labels" . | nindent 4 }}
  name: workspace-webhook-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "workspace-operator.selectorLabels" . | nindent 4 }}
