annotations:
  category: Analytics
  images: |
    - name: fluentd
      image: docker.io/bitnami/fluentd:1.16.4-debian-12-r0
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.16.4
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Fluentd collects events from various data sources and writes them to
  files, RDBMS, NoSQL, IaaS, SaaS, Hadoop and so on.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/fluentd/img/fluentd-stack-220x234.png
keywords:
- fluentd
- logging
- logs
- data
- collector
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: fluentd
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/fluentd
version: 5.19.1
