# Default values for pipelinewatch-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pipelinewatch
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 242

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name: ""
  secret: "registrypullsecret"

container:
  port: 6063

appConfig:
  env: "dev"
  CONFIG_CENTER_ENABLED: false
  CONFIG_CENTER_BASE_URL:
podAnnotations: {}

deploymentAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 6063

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

readinessProbe: {}

updateStrategy: {}

extraEnv: {}

extraEnvYaml: {}
