{{- if .Values.serviceAccount.create -}}
apiVersion: v1
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range $key, $secret := .Values.imagePullSecrets }}
  - name: {{ $secret.name }}
{{- end }}
{{- end }}
kind: ServiceAccount
metadata:
  name: {{ include "bff-cli.serviceAccountName" . }}
  labels:
    {{- include "bff-cli.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}