{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
  {{- if .Values.ingress.annotations }}
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        {{- if and .Values.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: {{ .Values.ingress.pathType }}
        {{- end }}
        backend:
          service:
            name: {{ template "fullname" . }}
            port: 
              number: {{ .Values.service.externalPort }}
    {{- if ne .Values.ingress.hostname "*" }}
    host: {{ .Values.ingress.hostname }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts: 
      - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-secret" .Values.ingress.hostname }}
  {{- end }}
{{- end -}}
