apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cli-pvc-clusterrole
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]