# Default values for workflow-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pilotdataplatform.azurecr.io/workflow-manager
  pullPolicy: Always
  tag: "2.0.0"


appConfig:
  tenant_id: ""
  kafka_url: "kafka.utility:9092"
  kafka_topic: "metadata.items.activity"
  rabbitmq: "rabbitmq.workflow"
  rabbitmq_port: "5672"
  rabbitmq_user: "workflow"
  rabbitmq_concurrent_consumers: "10"
  rabbitmq_max_concurrent_consumers: "20"
  db_url: "jdbc:postgresql://workflow-db-postgresql:5432/workflows"
  workflows_namespace: "workflow"
  notification_url: "http://notification.utility:5065/v1"
  weblog_url: "http://nf-weblog.workflow:5075/v1"

extraEnv: {}
extraEnvYaml:
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: workflow-db-postgresql
        key: postgres-password
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: workflow-db-postgresql
        key: postgres-password
  - name: SPRING_RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rabbitmq
        key: rabbitmq-password

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "workflow-manager-sa"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9081

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
