{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pipelinewatch-service.serviceAccountName" . }}
imagePullSecrets:
- name: {{ .Values.serviceAccount.secret }}
{{- end }}
