{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "base-job.fullname" . }}
  labels:
    {{- include "base-job.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.rules }}
rules:
{{- toYaml . | nindent 2 }}
{{- end}}
{{- end}}
