apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
spec:
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      {{- if .Values.serviceAccount.create}}
      serviceAccountName: {{ include "base-job.serviceAccountName" . }}
      {{- end }}
      containers:
      - name: {{ .Values.container.name }}
        image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
      {{- with .Values.volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 10 }}
      {{- end }}
        {{- if or .Values.container.env .Values.container.extraEnvYaml}}
        env:
        {{- range $key, $value := .Values.container.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
{{- with .Values.container.extraEnvYaml }}
        {{- toYaml . | nindent 10 }}
{{- end }}
        {{- end }}
      restartPolicy: {{ .Values.job.restartPolicy }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
