apiVersion: v1
kind: Service
metadata:
  name: {{ include "bff.fullname" . }}
  labels:
    {{- include "bff.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ include "bff.fullname" . }}
    - port: {{ .Values.service.portalPort }}
      targetPort: {{ .Values.service.portalTargetPort }}
      protocol: TCP
      name: portal-{{ include "bff.fullname" . }}
  selector:
    {{- include "bff.selectorLabels" . | nindent 4 }}
