apiVersion: v1
kind: Service
metadata:
  name: {{ include "bff.fullname" . }}
  labels:
    {{- include "bff.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName | default (include "bff.fullname" .) }}
    - port: {{ .Values.service.portalPort }}
      targetPort: {{ .Values.service.portalTargetPort }}
      protocol: TCP
      name: {{ .Values.service.portalPortName | default (printf "portal-%s" (include "bff.fullname" .)) }}
  selector:
    {{- include "bff.selectorLabels" . | nindent 4 }}
