apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cli-pvc-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: cli-automation-pvc-cli-automation-public-bucket
  namespace: doubledouble-cli
roleRef:
  kind: ClusterRole
  name: cli-pvc-clusterrole
  apiGroup: rbac.authorization.k8s.io
