# Default values for dataops-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---

replicaCount: 1

image:
  repository: dataops
  pullPolicy: Always
  tag: 274

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name:

container:
  port: 5063

appConfig:

  env: "dev"
  CONFIG_CENTER_ENABLED: false
  CONFIG_CENTER_BASE_URL:

  tenant_id: ""


  OPEN_TELEMETRY_ENABLED: true
  HOST: 0.0.0.0
  RDS_HOST: 'postgres.utility'
  RDS_PORT: 5432
  RDS_NAME: "dataops"
  RDS_USERNAME: 'postgres'
  RDS_SCHEMA: "public"
  RDS_ECHO_SQL_QUERIES: false

  REDIS_HOST: redis-master.redis
  REDIS_PORT: 6379
  REDIS_DB: 0

  WORKERS: 2

podAnnotations: {}

deploymentAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 5063

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

readinessProbe: {}

updateStrategy: {}

extraEnv: {}

extraEnvYaml: {}
