apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.cronjob.ttlSecondsAfterFinished }}
      template:
        spec:
          containers:
          - name: {{ .Values.container.name }}
            image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
            {{- if .Values.container.env }}
            env:
            {{- range .Values.container.env }}
              - name: {{ .name }}
                value: {{ .value }}
            {{- end }}
            {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{- if .Values.volume.enabled }}
          volumes:
          - name: {{ .Values.volume.name }}
            persistentVolumeClaim:
              claimName: {{ .Values.volume.clainName }}
          {{- end }}
