apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.cronjob.ttlSecondsAfterFinished }}
      template:
        spec:
          {{- if .Values.serviceAccount.create}}
          serviceAccountName: {{ include "base-cronjob.serviceAccountName" . }}
          {{- end }}
          containers:
          - name: {{ .Values.container.name }}
            image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
            {{- with .Values.volumeMounts }}
            volumeMounts:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if or .Values.container.env .Values.container.extraEnvYaml}}
            env:
            {{- range $key, $value := .Values.container.env }}
              - name: {{ $key }}
                value: {{ $value | quote }}
            {{- end }}
            {{- with .Values.container.extraEnvYaml }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
